### ISSUE TITLE
Roadmap 0.1.0

### ISSUE THREAD

**Issue by rlouf** [rlouf/mcx#1]
## Diagnostics

- [ ] Effective sample size
- [ ] Rhat
- [ ] Simulation-based calibration

## Inference

- [x] Random walk metropolis
- [ ] Hamiltonian Monte Carlo
- [ ] Empirical HMC
- [ ] Sequential MCMC

## Misc

- [ ] Iterative sampling
- [ ] Trace to Arviz
- [ ] Transforms
- [ ] Support static check

## Distributions

- [ ] Bernoulli
- [ ] Beta
- [ ] Categorical
- [ ] Cauchy
- [ ] Dirichlet
- [ ] Discrete Uniform
- [ ] Gamma
- [ ] Laplace
- [ ] Log Normal
- [ ] Multinomial
- [ ] Multivariate Normal
- [ ] Normal
- [ ] Uniform

## BNNs

- [ ] Serial distribution 
- [ ] Dense layer
- [ ] Softmax
- [ ] ReLu

## Processes

- [ ] Gaussian Process

**Comment by rlouf** [comment]
What it is not about:

- NUTS
- Discontinuous HMC
- Riemannian manifold Hamiltonian Monte Carlo
- Particle Filtering / Sequential Monte Carlo
- HMC augmented with NN
- More distributions
- Stochastic processes
- Simulation-based calibration
- Population predictive check
- Rao-Blackwellization

**Comment by rlouf** [comment]
To make the core more robust we could simply create `DistributionDef` and `Sample` ast nodes. MCX's ast would thus be a superset of Python's.

- Functions decorated with `@mcx.model` inside a model become `DistributionDef` instead of `FunctionDef`;
- Random variable assignments `x <~ Normal(0, 1)` become assignments with a `Sample` node on the right instead of a `Call` node.

The internals would have the following structure:

```
MODEL DEFINITION ---> PYTHON AST --+------------> MCX AST
 | @mcx.model                      |                 ^
 | <~                              |                 |
                                   |                 |
                                   +------> Probabilistic Graphical Model
```

MCX implements several 'compilers' that can compile the AST in different functions depending
on the context:

- logpdf
- forward sampling function
- posterior sampling function
- function to sample from the deterministic variables

We would like to also store an intermediate representation, a graph that summarizes the relation between the random and deterministic variables. This would allow manipulation of the graphical model at a higher level than rewrite of the AST code. Modifying the graphical model would modify the underlying AST as well.

**Comment by elanmart** [comment]
Hi @rlouf , I was searching for the `do-operator` recently, and it seems it got removed at some point. 

Are there any plans to add it back? It is marked as "done" in the roadmap above. I can hack around it, but it would be super useful for some code examples in Rethinking :sweat_smile:

**Comment by rlouf** [comment]
I took it off because the implementation would be a lot different; the design I had in my was that when we use `.do(a=10)` the variable `a` now becomes an argument to every target function and we partially apply these with `a`'s value. Not as simple as before but I would definitely appreciate a PR adding this to MCX.
